name: Generate file-based catalogs

on:
  push:
    branches:
      - main
    paths:
      - 'hack/update-bundle-*.sh'

env:
  BRANCH: actions/generate-catalog

jobs:
  update-catalog:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Log into registry.redhat.io
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REGISTRY_USERNAME }}
          password: ${{ secrets.RH_REGISTRY_PASSWORD}}

      - name: Get catalog sha
        id: get-catalog-sha
        # Assumes only one update-bundle-*.sh file changes per commit; uses the first match.
        run: |
          changed_file=$(git log -1 --pretty=format:'' --name-only | grep 'hack/update-catalogs-.*\.sh' | head -1)
          echo "catalog-sha=$(grep 'bundle@sha256' "$changed_file" | cut -d ':' -f 2- | tr -d '"')" >> "$GITHUB_OUTPUT"
          echo "catalog-short-sha=$(grep 'bundle@sha256' "$changed_file" | cut -d ':' -f 2- | cut -b -7 | tr -d '"')" >> "$GITHUB_OUTPUT"

      - name: Generate catalog
        run: |
          make generate-catalog

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore: generate catalog for bundle ${{ steps.get-catalog-sha.outputs.catalog-short-sha }}"
          title: "Generate file-based catalogs for bundle ${{ steps.get-catalog-sha.outputs.catalog-short-sha }}"
          body: "Update the catalogs to bundle sha ${{ steps.get-catalog-sha.outputs.catalog-sha }}."
          branch: ${{ env.BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
