name: Pre-submit tests
on:
  pull_request:

jobs:
  generate:
    name: Verify generated code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry.redhat.io
        shell: bash
        env:
          RH_REGISTRY_USERNAME: ${{ secrets.RH_REGISTRY_USERNAME }}
          RH_REGISTRY_PASSWORD: ${{ secrets.RH_REGISTRY_PASSWORD }}
        run: |
          echo "$RH_REGISTRY_PASSWORD" | docker login --username "$RH_REGISTRY_USERNAME" --password-stdin registry.redhat.io
      - run: make --always-make generate && git diff --exit-code
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make --always-make lint
