name: Test

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Test secrets
        env:
          RH_REGISTRY_USERNAME: ${{ secrets.RH_REGISTRY_USERNAME_TEST }}
          RH_REGISTRY_PASSWORD: ${{ secrets.RH_REGISTRY_PASSWORD_TEST }}
        run: |
          echo "Username length: ${#RH_REGISTRY_USERNAME}"
          echo "Password length: ${#RH_REGISTRY_PASSWORD}"
