name: Pre-submit tests
on:
  pull_request:

jobs:
  generate:
    name: Verify generated code
    runs-on: ubuntu-latest
    steps:
      - name: Log in to registry.redhat.io
        env:
          RH_REGISTRY_USERNAME: ${{ secrets.RH_REGISTRY_USERNAME }}
          RH_REGISTRY_PASSWORD: ${{ secrets.RH_REGISTRY_PASSWORD }}
        run: |
          if [ -v "RH_REGISTRY_USERNAME" ] && [ -v "RH_REGISTRY_PASSWORD" ]
          then
            podman login registry.redhat.io --username "$RH_REGISTRY_USERNAME" --password-stdin <<<"$RH_REGISTRY_PASSWORD"
          else
            echo "Login to registry before running this script"
            exit 1
          fi
      - uses: actions/checkout@v4
      - run: make --always-make generate && git diff --exit-code
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make --always-make lint
