name: Pre-submit tests

on:
  pull_request:

jobs:
  generate:
    name: Verify generated code
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to registry.redhat.io
        run: |
          echo "Checking RH_REGISTRY_USERNAME length: ${#RH_REGISTRY_USERNAME}"
          if [ -n "$RH_REGISTRY_USERNAME" ] && [ -n "$RH_REGISTRY_PASSWORD" ]; then
            echo "$RH_REGISTRY_PASSWORD" | docker login registry.redhat.io \
              --username "$RH_REGISTRY_USERNAME" --password-stdin
            echo "Login successful"
          else
            echo "Missing credentials"
            exit 1
          fi
        env:
          RH_REGISTRY_USERNAME: ${{ secrets.RH_REGISTRY_USERNAME }}
          RH_REGISTRY_PASSWORD: ${{ secrets.RH_REGISTRY_PASSWORD }}

      - name: Run code generation and check diffs
        run: make --always-make generate && git diff --exit-code

      - name: Show secret length for debug
        run: echo "Length of RH_REGISTRY_USERNAME is ${#RH_REGISTRY_USERNAME}"
        env:
          RH_REGISTRY_USERNAME: ${{ secrets.RH_REGISTRY_USERNAME }}

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - run: make --always-make lint
